- hosts: all
  become: true
  vars:
          - java_version: java-1.8.0-openjdk
          - tomcat_version: https://downloads.apache.org/tomcat/tomcat-8/v8.5.70/bin/apache-tomcat-8.5.70.tar.gz
          - tomcat_file: /opt/apache-tomcat-8.5.70.tar.gz
          - tomcat_port: 9080
  tasks:
          - name: install Java
            yum:
                    name: "{{ java_version }}"
                    state: present

          - name: Download tomcat8
            get_url:
                    url: "{{ tomcat_version }}"
                    dest: /opt/

          - name: extract the tar file
            unarchive:
                    src: "{{ tomcat_file }}"
                    dest: /opt/
                    remote_src: yes

          - name: renaming the tomcat file
            command: mv /opt/apache-tomcat-8.5.70 /opt/tomcat8

          - name: change the owner of tomcat8
            file:
                    path: /opt/tomcat8
                    state: directory
                    recurse: yes
                    owner: ec2-user
                    group: ec2-user

          - name: remove unwanted files
            file:
                    path: /opt/{{ tomcat_file }}
                    state: absent
          - name: start the tomcat server
            shell: nohup /opt/tomcat8/bin/startup.sh &

          - name: change the tomcat port
            template:
                    src: server.xml.j2
                    dest: /opt/tomcat8/conf/server.xml
            notify:
                    - start and stop the tomcat

  handlers:
          - name: start and stop the tomcat
            shell: "{{ item }}"
            loop:
                    - nohup /opt/tomcat8/bin/shutdown.sh &
                    - nohup /opt/tomcat8/bin/startup.sh &
